[package]
name = "ffs-tui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ffs = { workspace = true }
ftui = { workspace = true }

[lints]
workspace = true
